[package]
name = "vibe-httpd"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
license = "MIT"
description = "The vibeOS HTTP server"
repository = "https://github.com/vibedOS/vibe-httpd"

[dependencies]
vibe-rt = { git = "https://github.com/vibedOS/vibe-rt", rev = "e066720e6fffa26bba658d49c7911894c9befa59" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = "symbols"
